version: '3'

services:
  devbook:
    container_name: auth-api
    build: .
    image: golang:1.20
    volumes:
      - ./:/go/src/app
    ports:
      - 5000:5000

  mysql:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devbook
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /opt/mysql_data:/var/lib/mysql