version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - app.env
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  migrate:
    image: migrate/migrate
    volumes:
        - ./api/db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://caixeta:senhaqueninguemnuncavaipensarKEKW@db:5432/auth-api?sslmode=disable", "up"]
    depends_on: 
        - db
  app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - db

volumes:
  dbdata:
